# *Tensors*

Creating Tensors in Pytorch

In [ ]:
#pip install torch torchvision torchaudio

In [ ]:
#pip install torch==1.8.1+cu102 torchvision==0.9.1+cu102 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 804.1MB 21kB/s 
     |████████████████████████████████| 17.3MB 202kB/s 
     |████████████████████████████████| 1.9MB 23.2MB/s 
  Found existing installation: torch 1.8.1+cu101
    Uninstalling torch-1.8.1+cu101:
      Successfully uninstalled torch-1.8.1+cu101
  Found existing installation: torchvision 0.9.1+cu101
    Uninstalling torchvision-0.9.1+cu101:
      Successfully uninstalled torchvision-0.9.1+cu101


In [1]:
import torch

print(torch.__version__)

1.8.1+cu102


In [2]:
x = torch.Tensor(5,3) # generate a tensor
print(f'printing x ------------------------------------')
print()
print(x)
print()

y = torch.rand(5,3) # generate random matrix of floats
print(f'printing y ------------------------------------')
print()
print(y)

# generate random tensor within a specified interval
z = torch.randint(10,100,(2,3))
print(f'printing z -----------------------------------')
print()
print(z)

printing x ------------------------------------

tensor([[1.8469e+25, 8.7126e-04, 2.6451e+20],
        [4.4264e+30, 3.4059e-15, 7.3988e+31],
        [4.4849e+21, 2.7370e+20, 6.4640e-04],
        [7.9290e+29, 7.5546e+31, 1.6932e+22],
        [6.9722e+22, 1.7973e+19, 2.9967e+32]])

printing y ------------------------------------

tensor([[0.0393, 0.3974, 0.7390],
        [0.1421, 0.3758, 0.2068],
        [0.1621, 0.9385, 0.3986],
        [0.7020, 0.5487, 0.4531],
        [0.2071, 0.4329, 0.4779]])
printing z -----------------------------------

tensor([[48, 27, 39],
        [17, 43, 33]])


**Getting the shape of a tensor**

The shape indicates the dimensions of the tensor and the total
number of dimensions that would be used to infer the rank of the tensor

In [ ]:
a = torch.tensor([[0.1,0.2], [0.3,0.4]])
print(a)
print()

print(f'printing the shape of a')
print('--------------------------')
print(a.shape)

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

printing the shape of a
--------------------------
torch.Size([2, 2])


In [ ]:
b = torch.tensor([[0.1, 0.2],[0.3, 0.4],[0.5, 0.6]])
b.shape

torch.Size([3, 2])

In [ ]:
# Creating Tensors with Arbitrary Dimensions

c = torch.tensor([[[0.1],[0.2]],[[0.3],[0.4]],[[0.5],[0.6]]])
print(c)
print()
c.shape

tensor([[[0.1000],
         [0.2000]],

        [[0.3000],
         [0.4000]],

        [[0.5000],
         [0.6000]]])



torch.Size([3, 2, 1])

In [ ]:
# Creating Tensors with NumPy

import numpy as np

a = torch.tensor(np.array([[0.1,0.2], [0.3, 0.4]]))
print(a)

print()
a.shape

tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)



torch.Size([2, 2])

In [ ]:
# Creating Tensors from NumPy

a = np.array([1,2,3,4,5])
tensor_a = torch.from_numpy(a)
print(tensor_a)

tensor([1, 2, 3, 4, 5])


Tensors are multi-dimensional
arrays of the same type. We can specify the type when we construct a
tensor. In the following examples, we initialize the tensor with 32-bit
floating point numbers, 64-bit floating-point numbers, and 16-bit floating
point numbers. PyTorch defines a total of eight types

In [ ]:
# Defining Tensor Datatypes

print(f'Printing the 32-bit tensor')
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float32)
print(a)
print()

print(f'Printing the 64-bit tensor')
a = torch.tensor([[0.1, 0.2],[0.3, 0.4]], dtype=torch.float64)
print(a)

Printing a 32-bit tensor
tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]])

Printing a 64-bit tensor
tensor([[0.1000, 0.2000],
        [0.3000, 0.4000]], dtype=torch.float64)


In [ ]:
# Creating a Tensor with Random Values

r = torch.rand(2,2,2)
print(r)
print()
print(r.shape)

tensor([[[0.6289, 0.0660],
         [0.8904, 0.8841]],

        [[0.2286, 0.5962],
         [0.4001, 0.3141]]])

torch.Size([2, 2, 2])


In [ ]:
# Creating a Tensor Having All Zeros

zeros = torch.zeros(2,2,4)
print(zeros)
print()

print(zeros.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

torch.Size([2, 2, 4])


In [ ]:
# Creating a Tensor Having All Ones

ones = torch.ones(2,2,3)
print(ones)
print()

print(ones.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

torch.Size([2, 2, 3])


In [ ]:
# Creating an Identity Matix Tensor

i = torch.eye(3)
print(i)
print()

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# Creating a Tensor Filled with an Arbitrary Value

f = torch.full((5,5), 0.8)
print(f)

tensor([[0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000, 0.8000, 0.8000],
        [0.8000, 0.8000, 0.8000, 0.8000, 0.8000]])


In [ ]:
# Creating a Tensor with Linearly Spaced Floating-Point Numbers

lin = torch.linspace(0, 20, steps=10)
print(lin)

tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])


In [ ]:
# Creating a Tensor with Logarithmically Spaced Floating-Point Numbers

log = torch.logspace(-3,3,10) #create 10 logarithmically spaced floats
log

tensor([1.0000e-03, 4.6416e-03, 2.1544e-02, 1.0000e-01, 4.6416e-01, 2.1544e+00,
        1.0000e+01, 4.6416e+01, 2.1544e+02, 1.0000e+03])

In [ ]:
# Creating a Tensor with Dimensions Similar to Another Tensor

a = torch.tensor([[0.5,0.5], [0.5,0.5]])
print(a)
print()

b = torch.zeros_like(a)
print(b)
print()

c = torch.ones_like(a)
print(c)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

tensor([[0., 0.],
        [0., 0.]])

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Creating a Tensor with a Range of Integers

a = torch.arange(1,10, step=2)
print(a)
print()

a = torch.arange(1.0,10, step=2)
print(a)

tensor([1, 3, 5, 7, 9])

tensor([1., 3., 5., 7., 9.])


In [ ]:
# Creating a Tensor with a Random Permutation of Integers

r = torch.randperm(10)
print(r)

tensor([2, 0, 8, 9, 4, 3, 7, 5, 6, 1])


**Tensor Munging Operations**

We will start by looking at accessing individual elements of a tensor. The following example should be familiar, as it is identical to the list indexing operator in Python.

In [ ]:
# Accessing Individual Members of a Tensor

a = torch.tensor([[1,2],[3,4]])

print(a[0][0])

print(a[0][1])

print(a[1][0])

print(a[1][1])

tensor(1)
tensor(2)
tensor(3)
tensor(4)


In [ ]:
# Reshaping a Tensor

a = torch.zeros(10)
print(a)
print()

print(a.shape)

print()
b = a.view(2,5)
print(b)
print()

print(b.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

torch.Size([10])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

torch.Size([2, 5])


In [ ]:
# Concatenating Two Tensors

a = torch.zeros(2,2)
print(a)
print()
print(a.shape)
print()

b = torch.cat([a,a,a],0)
print(b)
print()
print(b.shape)
print()

c = torch.cat([a,a,a],1)
print(c)
print()
print(c.shape)

tensor([[0., 0.],
        [0., 0.]])

torch.Size([2, 2])

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

torch.Size([6, 2])

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

torch.Size([2, 6])


In [ ]:
# Stacking Tensors

a = torch.zeros(2,2)
print(a)
print(a.shape)
print()

b = torch.stack([a,a,a],0)
print(b)
print(b.shape)
print()

c = torch.stack([a,a,a],1)
print(c)
print(c.shape)

tensor([[0., 0.],
        [0., 0.]])
torch.Size([2, 2])

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([3, 2, 2])

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
torch.Size([2, 3, 2])


The index_select method allows you to extract parts of a tensor along
a given dimension. Note that the method takes three arguments: the tensor
to operate on, the dimension along which to extract data, and the tensor
containing the indices.

In [ ]:
# Extracting Parts of Tensors Using index_select

a = torch.FloatTensor([[1 ,2, 3],[4, 5, 6], [7, 8, 9]])
print(a)
print(a.shape)
print()

index = torch.LongTensor([0, 1])

b = torch.index_select(a,0,index)
print(b)
print(b.shape)
print()

c = torch.index_select(a,1,index)
print(c)
print(c.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])

tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])
torch.Size([3, 2])


In [ ]:
# Reshaping a Tensor with the squeeze Method

## The squeeze method removes all dimensions with a value of one,

a = torch.zeros(2,2,1)
print(a)
print(a.shape)
print()

b = torch.unsqueeze(a, 0)
print(b)
print()

c = torch.unsqueeze(a,1)
print(c)
print(c.shape)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
torch.Size([2, 2, 1])

tensor([[[[0.],
          [0.]],

         [[0.],
          [0.]]]])

tensor([[[[0.],
          [0.]]],


        [[[0.],
          [0.]]]])
torch.Size([2, 1, 2, 1])


In [ ]:
# Constructing a Tensor from an Existing Tensor Using
# the where Method

a = torch.zeros(3,3)
print(a)
print(a.shape)
print()

b = torch.ones(3,3)
print(b)
print(b.shape)
print()

c = torch.rand(3,3)
print(c)
print()

d = torch.where(c > 0.5, a, b)
print(d)
print(d.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])

tensor([[0.0315, 0.5365, 0.5475],
        [0.8006, 0.8605, 0.0518],
        [0.2429, 0.0222, 0.2058]])

tensor([[1., 0., 0.],
        [0., 0., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


**Element-Wise Mathematical Operations**

Let us now take a look at a number of element-wise mathematical
operations. These operations are called element-wise mathematical
operations because an identical operation being performed on each of the
elements of the tensor.

In [ ]:
# Element-Wise Multiplication

a = torch.rand(3,3)
print(a)
print()

b = torch.FloatTensor([[0, 1, 0],[1,1,1],[0,1,0]])
print(b)
print()

c = torch.mul(a,b)
print(c)

tensor([[1.9012e-02, 1.8993e-01, 7.8799e-03],
        [4.8984e-01, 9.3385e-01, 2.6009e-01],
        [6.5214e-02, 9.7557e-01, 6.0445e-04]])

tensor([[0., 1., 0.],
        [1., 1., 1.],
        [0., 1., 0.]])

tensor([[0.0000, 0.1899, 0.0000],
        [0.4898, 0.9338, 0.2601],
        [0.0000, 0.9756, 0.0000]])


In [ ]:
# Element-Wise Division

a = torch.rand(3,3)
print(a)
print()

b = torch.FloatTensor([[1, 2, 1],[2,2,2],[1,2,1]])
print(b)
print()

c = torch.div(a,b)
print(c)

tensor([[0.0044, 0.3691, 0.2695],
        [0.6151, 0.3484, 0.7172],
        [0.9973, 0.3192, 0.3253]])

tensor([[1., 2., 1.],
        [2., 2., 2.],
        [1., 2., 1.]])

tensor([[0.0044, 0.1845, 0.2695],
        [0.3075, 0.1742, 0.3586],
        [0.9973, 0.1596, 0.3253]])


**Linear Algebraic Operations**

In [ ]:
a = torch.ones(2,3)
print(a)
print()

b = torch.ones(3,2)
print(b)
print()

c = torch.matmul(a,b)
print(c)
print(c.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

tensor([[3., 3.],
        [3., 3.]])
torch.Size([2, 2])


*Building a Neural Network in PyTorch*

The creation of neural networks in PyTorch is done via the nn.Module.
This is a base class, and we use inheritance to access it. After the
import, we will be able to use all the functionality of nn.Module base
class, but we will still have the overwriting capabilities of the base class
for forward pass/ model construction through the network.

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

We import the nn.Module class through inheritance. In the first line of
our class initialization, that is, def \__init__(self): we have the super()
function. This will create an instance of the base class, that is,
nn.Module. The next three lines have then been used to create fully
connected layers of the neural network. The nn.Linear object
represents a fully connected. The first argument in this definition
denotes the number of nodes in layer. The next argument denotes the
number of nodes in the layer l + 1. The first layer will take 28 * 28
input pixels and it will connect to the first 200 node hidden layer. We
then have 200 to 200 hidden layers then a connection between the
hidden layer and the output layer with a total of 10 nodes

In [ ]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(28*28, 200)
    self.fc2 = nn.Linear(200, 200)
    self.fc3 = nn.Linear(200, 10)

  
  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)

    return F.log_softmax(x)

In the forward() method defined above, we have passed the input data
x to be the primary argument. This has then been fed into the first
fully connected layer, that is, self.fc1(x). A ReLU activation function has
then been applied to the nodes in the layer via F.relu() . The network is
hierarchical in nature, hence we have added x at every stage, so that it
can be fed into the next layer. This has been through the three fully
connected layers, except the last one, where we have used a log
softmax activation function rather than ReLU. This, when combined
with negative log likelihood loss function returns a multi-class cross
entropy based loss function that will be used for training the network.


Next, we need to create an instance of our network architecture:

In [ ]:
net = Net()

print(net)

Net(
  (fc1): Linear(in_features=784, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=200, bias=True)
  (fc3): Linear(in_features=200, out_features=10, bias=True)
)


*Training*

It is now time for us to train the network. We should begin by setting
up an optimizer and a loss criterion:

In [ ]:
# Let’s first create a stochastic gradient descent optimizer

import torch.optim as optim


learning_rate = 0.001

optimizer = optim.SGD(net.parameters(), lr=learning_rate,
                      momentum=0.9)


# Then we create a loss function
criterion = nn.NLLLoss()